services:
  dashboard:
    build:
      context: .
      dockerfile: Dockerfile.dashboard
    ports:
      - "5000:5000"
    command: python dashboard/dashboard_app.py
    depends_on:
      - redis
      - chatgpt_worker
      - quiz_automation_worker
      - typecast_worker
  backend-api:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "5001:5000"
    command: python src/app.py
    depends_on:
      - redis
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
  chatgpt_worker:
    build:
      context: .
      dockerfile: Dockerfile.puppeteer
    command: node chatgpt_worker.js
    depends_on:
      - redis
  quiz_automation_worker:
    build:
      context: .
      dockerfile: Dockerfile.puppeteer
    command: node quiz_automation_worker.js
    depends_on:
      - redis
  typecast_worker:
    build:
      context: .
      dockerfile: Dockerfile.puppeteer
    command: node typecast_worker.js
    depends_on:
      - redis