version: '3.8'

services:
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    networks:
      - munjero_network

  websocket_server:
    build:
      context: .
      dockerfile: Dockerfile
    command: python scripts/websocket_server.py
    ports:
      - "8765:8765"
    depends_on:
      - redis
    networks:
      - munjero_network
    volumes:
      - .:/app # Mount for live changes during development

  agent_app:
    build:
      context: .
      dockerfile: Dockerfile
    command: python scripts/agent_app.py
    depends_on:
      - redis
    networks:
      - munjero_network
    volumes:
      - .:/app # Mount for live changes during development

  dashboard_app:
    build:
      context: .
      dockerfile: Dockerfile
    command: python dashboard/dashboard_app.py
    ports:
      - "5000:5000"
    depends_on:
      - redis
    networks:
      - munjero_network
    volumes:
      - .:/app # Mount for live changes during development

networks:
  munjero_network:
    driver: bridge