FROM ghcr.io/puppeteer/puppeteer:21.7.0

# Skip downloading Chromium, as it's provided by the base image
ENV PUPPETEER_SKIP_DOWNLOAD=true

# Set environment variables for X11 (if needed, though the base image might handle this)
ENV DISPLAY=:0.0

USER root
RUN mkdir -p /home/pptruser/app && chown -R pptruser:pptruser /home/pptruser/app
USER pptruser
WORKDIR /home/pptruser/app

COPY puppeteer_worker/package*.json ./
RUN npm install

COPY puppeteer_worker/debug_x11.sh ./puppeteer_worker/
USER root
RUN chown pptruser:pptruser ./puppeteer_worker/debug_x11.sh
USER pptruser
RUN chmod +x ./puppeteer_worker/debug_x11.sh

COPY puppeteer_worker/worker.js ./puppeteer_worker/
COPY puppeteer_worker/typecast_worker.js ./puppeteer_worker/
COPY puppeteer_worker/chatgpt_worker.js ./puppeteer_worker/
COPY puppeteer_worker/quiz_automation_worker.js ./puppeteer_worker/
ENTRYPOINT ["/sbin/tini", "--"]
CMD ["node", "./puppeteer_worker/worker.js"]