version: '3.8'
services:
  redis:
    image: 'redis:7-alpine'
    ports:
      - '6380:6379'
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data

  websocket_server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8766:8765'
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - WS_PORT=8765
    command: bash -c "python /app/scripts/check_port.py 8765 WS_PORT 8765 && python /app/scripts/websocket_server.py"
    volumes:
      - ./scripts:/app/scripts
      - ./requirements.txt:/app/requirements.txt

  dashboard:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '5000:5000'
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - DASHBOARD_PORT=5000
    command: bash -c "python /app/scripts/check_port.py 5000 DASHBOARD_PORT 5000 && python /app/dashboard/dashboard_app.py"
    volumes:
      - ./dashboard:/app/dashboard
      - ./scripts:/app/scripts
      - ./requirements.txt:/app/requirements.txt

  agent:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
    volumes:
      - ./scripts:/app/scripts
      - ./requirements.txt:/app/requirements.txt

volumes:
  redis_data: