FROM node:18-alpine

RUN apk add --no-cache chromium mesa-dri-gallium libexif udev ttf-freefont xorg-server xvfb dbus nss freetype harfbuzz icu-libs fontconfig libjpeg-turbo libpng libwebp libxcomposite libxdamage libxext libxfixes libxrandr libxrender libxscrnsaver libxshmfence libxxf86vm alsa-lib cairo cups-libs gdk-pixbuf glib gtk+3.0 pango libgcc libstdc++ libuuid zlib xdpyinfo

# Set environment variables for X11
ENV DISPLAY=:0.0

WORKDIR /app/puppeteer_worker

COPY puppeteer_worker/package*.json ./
RUN npm install

COPY puppeteer_worker/debug_x11.sh ./
RUN chmod +x debug_x11.sh


CMD ["node", "worker.js"]
