FROM python:3.9-slim-buster
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY dashboard/ dashboard/
COPY scripts/ scripts/
CMD ["python", "dashboard/dashboard_app.py"]