version: '3.8'
services:
  redis:
    image: 'redis:7-alpine'
    ports:
      - '6379:6379'
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data

  websocket_server:
    build:
      context: .
      dockerfile: Dockerfile.websocket
    ports:
      - '8765:8765'
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
    volumes:
      - ./scripts:/app/scripts
      - ./requirements.txt:/app/requirements.txt

  dashboard:
    build:
      context: .
      dockerfile: Dockerfile.dashboard
    ports:
      - '5000:5000'
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
    volumes:
      - ./dashboard:/app/dashboard
      - ./scripts:/app/scripts
      - ./requirements.txt:/app/requirements.txt

  agent:
    build:
      context: .
      dockerfile: Dockerfile.agent
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
    volumes:
      - ./scripts:/app/scripts
      - ./requirements.txt:/app/requirements.txt

volumes:
  redis_data: