version: '3.8'

services:
  redis:
    image: "redis:alpine"
    ports:
      - "6380:6379"

  nginx:
    image: nginx:latest
    ports:
      - "8080:80" # Expose Nginx on host port 8080
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro # Mount Nginx config
    depends_on:
      - websocket_server # Nginx depends on the websocket server

  # Base service definition for other Python services to extend
  app:
    build:
      context: .
      dockerfile: Dockerfile
    # Set the python path so that imports work correctly from any script
    environment:
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1 # Added for unbuffered output

  rq_worker:
    extends:
      service: app
    command: rq worker -u redis://redis:6379
    depends_on:
      - redis

  websocket_server:
    extends:
      service: app
    command: python /app/websocket_server.py
    mem_limit: 512m # Added memory limit
    depends_on:
      - redis

  agent_app:
    extends:
      service: app
    command: python /app/agent_app.py
    depends_on:
      - websocket_server

  dashboard:
    extends:
      service: app
    command: python /app/dashboard/dashboard_app.py
    ports:
      - "5001:5000"
    depends_on:
      - redis
